services:
  fast-note-sync-service:
    image: haierkeys/fast-note-sync-service:3.3.3
    container_name: fast-note-sync-service
    restart: unless-stopped
    ports:
      - "${HOST_BIND:-127.0.0.1}:9002:9000"
      - "${HOST_BIND:-127.0.0.1}:9003:9001"
    volumes:
      - ${FNS_DATA_DIR:-/data/fast-note-sync}/storage/:/fast-note-sync/storage/
      - ${FNS_DATA_DIR:-/data/fast-note-sync}/config/:/fast-note-sync/config/
    networks:
      - app-network  # 与 image-api 在同一网络1

networks:
  app-network:
    driver: bridge

