package code

var en_messages = map[int]string{
	0:   "Failed",
	1:   "Success",
	2:   "Create Success",
	3:   "Update Success",
	4:   "Delete Success",
	5:   "Password Update Success",
	6:   "No Update",
	300: "Server Internal Error",
	301: "Database query failed",
	302: "Server busy, please try again later",
	303: "Too Many Requests",
	304: "Not Found API",
	305: "Invalid Params",
	306: "Invalid Auth Token",
	307: "Not logged in. Please log in first.",
	308: "Session expired, please log in again.",
	309: "Your access is missing a user token",
	310: "Auth token has expired",
	311: "Token generation failed",
	312: "Auth token IP restricted",
	313: "Auth token Browser (UA) restricted",
	314: "Auth token Client restricted",
	315: "Auth token Scope restricted",

	// --- User Related (400-419) ---
	400: "User registration failed",
	401: "User login failed",
	402: "Invalid username or password",
	403: "Username does not exist",
	404: "Username already exists",
	405: "User email already exists",
	406: "The username does not meet the rules, the username length is 3-15 digits, and can only contain letters, numbers or underscores",
	407: "Password does not meet the rules",
	408: "Current password verification error",
	409: "The two passwords entered are inconsistent",
	410: "User registration is closed, please contact the administrator to configure the config.user.register-is-enable option",
	411: "This operation requires administrator privileges",
	412: "User local file system is disabled",
	413: "User update failed",
	414: "Cannot block an administrator",

	// --- Vault Related (420-429) ---
	420: "Note Vault does not exist",
	421: "Note Vault already exists",
	422: "Invalid storage type",
	423: "Invalid cloud storage type",

	// --- Note Related (430-444) ---
	430: "Note does not exist",
	431: "Note already exists",
	432: "Get note failed",
	433: "Note modify or create failed",
	434: "Modify note content failed",
	435: "Delete note failed",
	436: "Note list get failed",
	437: "Note rename failed",
	438: "Note rename target note already exists",
	439: "Sync note failed",
	440: "Note update check failed",
	441: "Destination note already exists",
	442: "No match found",
	443: "Invalid regex pattern",
	444: "Invalid path: path cannot contain '..'",

	// --- Folder Related (445-454) ---
	445: "Folder does not exist",
	446: "Folder already exists",
	447: "Get folder failed",
	448: "Folder modify or create failed",
	449: "Delete folder failed",
	450: "Folder list get failed",
	451: "Folder rename failed",

	// --- File/Attachment Related (455-469) ---
	455: "File does not exist",
	456: "Get file failed",
	457: "File modify or create failed",
	458: "Modify file content failed",
	459: "Delete file failed",
	460: "File list get failed",
	461: "Upload file failed",
	462: "File upload check failed",
	463: "Upload file session not found",
	464: "File save failed",
	465: "File move failed",
	466: "File read failed",
	467: "File already exists",

	// --- Setting Related (470-479) ---
	470: "Setting does not exist",
	471: "Setting already exists",
	472: "Get setting failed",
	473: "Setting modify or create failed",
	474: "Modify setting content failed",
	475: "Delete setting failed",
	476: "Setting list get failed",
	477: "Sync setting failed",
	478: "Setting update check failed",
	479: "Config save failed",

	// --- Share Related (480-489) ---
	480: "Share link not found",
	481: "Share link has expired",
	482: "Share link has been revoked",
	483: "Password required for viewing",
	484: "Invalid share password",

	// --- Sync & History (490-499) ---
	490: "Note modification conflict detected. Full content has been preserved and requires manual handling.",
	491: "History not found",
	492: "Failed to restore history",
	493: "Sync & backup task does not exist",
	494: "Failed to execute sync & backup task",
	495: "Unknown sync & backup type",
	496: "Sync & backup task ID is required",
	497: "Note repository ID is required",
	498: "Invalid storage ID list in sync & backup task settings",
	499: "Sync & backup task is disabled",
	500: "Storage configuration does not exist",
	501: "This storage type has been disabled",
	502: "Storage connection test failed",

	// Git Sync
	510: "Git sync configuration does not exist",
	511: "Git sync task is already running",
	512: "Git validation failed",
	520: "Cloudflared download failed",
	521: "Cloudflared binary not found, please download the tunnel program first",
}
